[package]
name = "v2ex-sign"
version = "0.1.0"
authors = ["石博文 <sbw@sbw.so>"]

[dependencies]
hyper = "*"
hyper-tls = "*"
tokio-core = "*"
futures = "*"
regex = "*"
lazy_static = "*"
clap = "*"
num_cpus = "*"